#pragma once

const int CHUNK_LOAD_THREADS = 4;
const int DEFAULT_CHUNK_LOAD_DISTANCE = 16;
//const int MAX_CHUNKS_IN_MEM = 128 * 4 * 128;
const int MAX_CHUNK_LOAD_DISTANCE = 50;
const int MAX_CHUNKS_IN_MEM = MAX_CHUNK_LOAD_DISTANCE * 4 * MAX_CHUNK_LOAD_DISTANCE;
